###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: projetodocker-redis

    mysql:
      image: mysql:5.7
      container_name: projetodocker-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=ProjetoDocker
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: projetodocker-webserver
      working_dir: /application
      volumes:
          - ./Musica:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: projetodocker-php-fpm
      working_dir: /application
      volumes:
        - ./Musica:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

